--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/WalleNetwork/Translation
build-by-default: true
branches:
- master
projects:
  Translation:
    path: ""
    model: virion
    type: library
...