--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/WalleNetwork/TranslationAPI
#build-by-default: true
branches:
- master
projects:
  TranslationAPI:
    path: ""
    model: virion
    type: library
...
